### ISSUE TITLE
Overrides Embers RSVP onerror default

### ISSUE THREAD

**Issue by jrhe** [201-created/ember-cli-airbrake#8]
Ember provides a customised default for RSVP.onerror. We override this and so it removes a lot of the behaviour they have added. No idea if we need all of this but one problem which manifested itself is the catching of TransitionAborted errors which the ember version filters out.

https://github.com/emberjs/ember.js/blob/85550ca7f91883838953e736caa6ef51daabf255/packages/ember-runtime/lib/ext/rsvp.js#L53

Theoretically we don't actually need to override this as it defaults to Ember.onerror if defined and we define it.

**Comment by jrhe** [comment]
Any comments about this? Why do we set both RSVPs error handler and Ember.onerror when RSVP delegates the the latter anyway automatically?

**Comment by bantic** [comment]
@jrhe Sorry, this issue got lost in the shuffle before. The latest version of this addon, 0.1.0, is a little more conservative about only registering error handlers for window.onerror and Ember.onerror. It also provides an `airbrake` service so that you can explicitly handle/notify errors however you would like. This may help address your issue. To use it, you'll want to remove `ember-cli-airbrake` from your `package.json` (and potentially also from your `node_modules/`) and `ember install ember-cli-airbrake@0.1.0`.
I'm closing this issue for now, please reopen if the updated package doesn't improve your situation. thanks!
